name: "AWS Academy Deploy"

on:
  push:
    branches:
      - main  # Se activa al subir cambios a la rama main

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    # Le dice a GitHub que entre en la carpeta "Terraform" donde esta mi código 
    defaults:
      run:
        working-directory: ./Terraform

    steps:
      # 1. Descarga mi código en la máquina de GitHub
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Instala Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Configura las credenciales de AWS Academy (usando Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }}
          aws-region: us-east-1

      # 4. Inicializa Terraform (conecta con el S3 bucket)
      - name: Terraform Init
        run: terraform init

      # 5. Crea/Actualiza la infraestructura (dominio, rds, ec2...)
      - name: Terraform Apply
        run: terraform apply -auto-approve
